from fastapi import APIRouter
from app.api.v1.endpoints import auth, users, lobs, projects, connectors, health, chatbot, audit, connector_catalog, project_connectors, connector_agents, health_runs, project_dashboard, health_rules, analytics, search, teams, components, metric_templates, project_connector_metrics, dashboard_templates, project_dashboard_assignments, aggregations, team_dashboard_assignments, lob_dashboard_assignments, rbac, settings, runtime, topology, batch_metrics, websocket, application_runtime, project_overview, proxy_settings
from app.dashboards_v2 import router as component_dashboard_assignments

api_router = APIRouter(prefix="/api/v1")

api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(rbac.router)
api_router.include_router(lobs.router)
api_router.include_router(projects.router)
api_router.include_router(teams.router)
api_router.include_router(components.router)
api_router.include_router(team_dashboard_assignments.router)
api_router.include_router(lob_dashboard_assignments.router)
api_router.include_router(component_dashboard_assignments.router)
api_router.include_router(connectors.router)
api_router.include_router(health.router)
api_router.include_router(health_runs.router)
api_router.include_router(chatbot.router)
api_router.include_router(audit.router)
api_router.include_router(connector_catalog.router)
api_router.include_router(metric_templates.router)
api_router.include_router(project_connectors.router)
api_router.include_router(project_connector_metrics.router)
api_router.include_router(connector_agents.router)
api_router.include_router(project_dashboard.router)
api_router.include_router(project_dashboard_assignments.router)
api_router.include_router(health_rules.router)
api_router.include_router(analytics.router)
api_router.include_router(search.router)
api_router.include_router(dashboard_templates.router)
api_router.include_router(aggregations.router)
api_router.include_router(settings.router)
api_router.include_router(runtime.router)
api_router.include_router(topology.router)
api_router.include_router(batch_metrics.router)
api_router.include_router(websocket.router)
api_router.include_router(application_runtime.router)
api_router.include_router(project_overview.router)
api_router.include_router(proxy_settings.router)
